adding new regression tests + fixed tests name collision

diff --git a/tests/riscv/riscv-vector-tests/run-test.sh.in b/tests/riscv/riscv-vector-tests/run-test.sh.in
--- a/tests/riscv/riscv-vector-tests/run-test.sh.in
+++ b/tests/riscv/riscv-vector-tests/run-test.sh.in
@@ -1,15 +1,19 @@
 #!/bin/bash
-RISCV_TOOLCHAIN_PATH=${RISCV_TOOLCHAIN_PATH:-$TOOLDIR"/riscv"$XLEN"-gnu-toolchain"}
 
+XLEN=${XLEN:-@XLEN@}
+TOOLDIR=${TOOLDIR:-"@TOOLDIR@"}
+RISCV_TOOLCHAIN_PATH=${RISCV_TOOLCHAIN_PATH:-"$TOOLDIR/riscv$XLEN-gnu-toolchain"}
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-RESTORE_PREV_DIR=$(pwd)
+TEST_DIR=${TEST_DIR:-"$SCRIPT_DIR/testcases"}
 
-VECTOR_TESTS_REPOSITORY=https://github.com/MichaelJSr/testcases/raw/main
+VECTOR_TESTS_REPOSITORY=https://github.com/MichaelJSr/testcases/raw/updated
 VECTOR_TESTS_BASE_NAME=vector-tests.tar.bz2
 
-vector_tests()
+set -e
+
+download_tests()
 {
-    parts=$(eval echo {a..l})
+    parts=$(eval echo {a..k})
     for x in $parts
     do
         wget $VECTOR_TESTS_REPOSITORY/$VECTOR_TESTS_BASE_NAME.parta$x
@@ -20,15 +24,13 @@ vector_tests()
 }
 
 # get selected testcases from command line or run default testcases
-if [ "$#" == "0" ];
-then
+if [ "$#" -eq 0 ]; then
   # write out test case name explicitely if there are collisions with other test names
   testcases=(vmv vslide vmerge vrgather \
-             vlm.v vsm.v \ 
              vle8 vle16 vle32 \
              vse8 vse16 vse32 \
+             vsseg vssseg vsuxseg vsoxseg \
              vlseg vlsseg vluxseg vloxseg \
-#            vsseg vssseg vsuxseg vsoxseg \ # fails for both XLEN 32 and 64
              vlse8 vlse16 vlse32 \
              vsse8 vsse16 vsse32 \
              vloxei vluxei vsoxei vsuxei \
@@ -52,66 +54,61 @@ then
              vsext vzext \
              vid)
   if [ $XLEN -eq 32 ]; then
-    testcases+=(vset) # fails for XLEN 64? Which doesn't make sense, since vset is essential, and other tests work
+    testcases+=()
   elif [ $XLEN -eq 64 ]; then
     testcases+=(vle64 vse64 vlse64 vsse64 vfwcvt vfncvt \
-#               vfwadd vfwsub \ # vfwadd.wf and vfwsub.wf fail, but .wv .vf and .vv pass
+                vfwadd vfwsub \
                 vfwmul vfwred vfwmacc vfwnmacc vfwmsac vfwnmsac )
   fi
 else
-  testcases="${@}"
+  testcases=("$@")
 fi
 
-cd $SCRIPT_DIR
-
-# Fallback #2: If testcases directory exists, we will use existing testcases
-if [ ! -d "$SCRIPT_DIR/testcases" ]; then
-  mkdir testcases
-  cd testcases
-  # Fallback #3: Otherwise, download testcases
-  vector_tests
+# Fallback #1: If testcases directory exists, use the existing testcases
+if [ ! -d "$TEST_DIR" ]; then
+  mkdir $TEST_DIR
+  pushd $TEST_DIR
+  if [ "$GEN_TESTS" -eq "1" ]; then
+    # Fallback #2: Generate testcases
+    /bin/bash ../gen-test.sh
+  else
+    # Fallback #3: Download testcases
+    download_tests
+  fi
+  popd
 fi
-
-cd $SCRIPT_DIR/testcases/v$VLEN"x"$XLEN
-
-# Fallback #1: Copy locally generated testcases (assuming they exist)
-rm *".ddr4.log"
-for testcase in ${testcases[@]}; do
-  rm "$testcase"*.elf "$testcase"*.bin "$testcase"*.dump "$testcase"*.log
-  cp -f $SCRIPT_DIR/../../../third_party/riscv-vector-tests/out/v"$VLEN"x"$XLEN"machine/bin/stage2/"$testcase"* .
-done
 
 passed=0
 failed=0
-selected=0
 
-# count all available testcases, exclude *.elf, *.bin, *.dump, *.log to prevent double counting
-all=$(($(ls | wc -l) - $(ls -d *.elf | wc -l) - $(ls -d *.bin | wc -l) - $(ls -d *.dump | wc -l) - $(ls -d *.log | wc -l)))
-
-for testcase in ${testcases[@]}; do
-  for f in "$testcase"* ; do 
-    ln -s "$f" "$f.elf";
-    "$RISCV_TOOLCHAIN_PATH"/bin/riscv"$XLEN"-unknown-elf-objdump -D "$f.elf" > "$f.dump";
-    "$RISCV_TOOLCHAIN_PATH"/bin/riscv"$XLEN"-unknown-elf-objcopy -O binary "$f.elf" "$f.bin";
-    $SCRIPT_DIR/../../../sim/simx/simx -v -c 1 "$f.bin" &> "$f.log";
-    if [ $? -eq 1 ]; then
-      echo "$f PASSED"
-      let "passed++"
+for testcase in "${testcases[@]}"; do
+  echo "Testcase: $testcase"
+  for f in $(find "$TEST_DIR/v${VLEN}x$XLEN" -type f -name "${testcase}*"); do
+    filename=$(basename "$f")
+    "$RISCV_TOOLCHAIN_PATH/bin/riscv$XLEN-unknown-elf-objdump" -D "$f" > "$filename.dump"
+    "$RISCV_TOOLCHAIN_PATH/bin/riscv$XLEN-unknown-elf-objcopy" -O binary "$f" "$filename.bin"
+    "$SCRIPT_DIR/../../../sim/simx/simx" -v "$filename.bin" > "$filename.log"
+    if [ $? -eq 0 ]; then
+      echo "$filename PASSED"
+      let "passed+=1"
     else
-      echo "$f FAILED"
-      let "failed++"
+      echo "$filename FAILED"
+      let "failed+=1"
     fi
     # REG_TESTS=1 informs the script to delete the previous binary after each vector test to save disk space
     # Otherwise, the vector regression tests would run out of disk space eventually
-    if [ -n "$REG_TESTS" ] && [ $REG_TESTS -eq 1 ]; then
-      cat $f.log
-      rm $f.*
-      rm $f
+    if [ "$REG_TESTS" -eq "1" ]; then
+      cat "$filename.log"
+      rm -f "$filename.bin" "$filename.dump" "$filename.log" > /dev/null 2>&1
     fi
-    let "selected++"
   done
 done
-cd $RESTORE_PREV_DIR
-echo "Passed $passed out of $selected selected vector tests."
-echo "Total available vector tests: $all"
+
+if [ "$failed" -eq "0" ]; then
+  echo "All $passed vector tests passed."
+else
+  total=$((passed + failed))
+  echo "$failed out of $total vector tests failed."
+fi
+
 exit $failed
